import type { EmojiPickerData } from './defs';

export const EMOJI_DATA: EmojiPickerData = [
  { name: 'Imp', emoji: '👿' },
  { name: 'Skull', emoji: '💀' },
  { name: 'Skull and Crossbones', emoji: '☠️' },
  { name: 'Pile of Poo', emoji: '💩' },
  { name: 'Clown Face', emoji: '🤡' },
  { name: 'Ogre', emoji: '👹' },
  { name: 'Goblin', emoji: '👺' },
  { name: 'Ghost', emoji: '👻' },
  { name: 'Alien', emoji: '👽' },
  { name: 'Alien Monster', emoji: '👾' },
  { name: 'Robot', emoji: '🤖' },
  { name: 'Grinning Cat', emoji: '😺' },
  {
    name: 'Grinning Cat with Smiling Eyes',
    emoji: '😸',
  },
  { name: 'See-No-Evil Monkey', emoji: '🙈' },
  { name: 'Hear-No-Evil Monkey', emoji: '🙉' },
  { name: 'Speak-No-Evil Monkey', emoji: '🙊' },
  { name: 'Anger Symbol', emoji: '💢' },
  { name: 'Collision', emoji: '💥' },
  { name: 'Dizzy', emoji: '💫' },
  { name: 'Sweat Droplets', emoji: '💦' },
  { name: 'Dash Symbol', emoji: '💨' },
  { name: 'Bomb', emoji: '💣' },
  { name: 'Speech Balloon', emoji: '💬' },
  { name: 'Left Speech Bubble', emoji: '🗨️' },
  { name: 'Right Anger Bubble', emoji: '🗯️' },
  { name: 'Thought Balloon', emoji: '💭' },
  { name: 'Zzz', emoji: '💤' },
  {
    name: 'Hand with Fingers Splayed',
    emoji: '🖐️',
  },
  { name: 'Ok Hand', emoji: '👌' },
  { name: 'Pinched Fingers', emoji: '🤌' },
  { name: 'Pinching Hand', emoji: '🤏' },
  { name: 'Victory Hand', emoji: '✌️' },
  { name: 'Crossed Fingers', emoji: '🤞' },
  {
    name: 'Hand with Index Finger and Thumb Crossed',
    emoji: '🫰',
  },
  { name: 'Love-You Gesture', emoji: '🤟' },
  { name: 'Sign of the Horns', emoji: '🤘' },
  { name: 'Call Me Hand', emoji: '🤙' },
  {
    name: 'Backhand Index Pointing Left',
    emoji: '👈',
  },
  {
    name: 'Backhand Index Pointing Right',
    emoji: '👉',
  },
  { name: 'Backhand Index Pointing Up', emoji: '👆' },
  { name: 'Middle Finger', emoji: '🖕' },
  {
    name: 'Backhand Index Pointing Down',
    emoji: '👇',
  },
  { name: 'Index Pointing at the Viewer', emoji: '🫵' },
  { name: 'Thumbs Up', emoji: '👍' },
  { name: 'Thumbs Down', emoji: '👎' },
  { name: 'Raised Fist', emoji: '✊' },
  { name: 'Oncoming Fist', emoji: '👊' },
  { name: 'Left-Facing Fist', emoji: '🤛' },
  { name: 'Right-Facing Fist', emoji: '🤜' },
  { name: 'Clapping Hands', emoji: '👏' },
  { name: 'Raising Hands', emoji: '🙌' },
  { name: 'Open Hands', emoji: '👐' },
  { name: 'Palms Up Together', emoji: '🤲' },
  { name: 'Handshake', emoji: '🤝' },
  { name: 'Handshake', emoji: '🤝🏿' },
  { name: 'Folded Hands', emoji: '🙏' },
  { name: 'Writing Hand', emoji: '✍️' },
  { name: 'Nail Polish', emoji: '💅' },
  { name: 'Flexed Biceps', emoji: '💪' },
  { name: 'Mechanical Arm', emoji: '🦾' },
  { name: 'Mechanical Leg', emoji: '🦿' },
  { name: 'Foot', emoji: '🦶' },
  { name: 'Ear', emoji: '👂' },
  { name: 'Nose', emoji: '👃' },
  { name: 'Brain', emoji: '🧠' },
  { name: 'Anatomical Heart', emoji: '🫀' },
  { name: 'Lungs', emoji: '🫁' },
  { name: 'Tooth', emoji: '🦷' },
  { name: 'Bone', emoji: '🦴' },
  { name: 'Eyes', emoji: '👀' },
  { name: 'Eye', emoji: '👁️' },
  { name: 'Baby', emoji: '👶' },
  { name: 'Child', emoji: '🧒' },
  { name: 'Boy', emoji: '👦' },
  { name: 'Girl', emoji: '👧' },
  { name: 'Adult', emoji: '🧑' },
  { name: 'Person Blond Hair', emoji: '👱' },
  { name: 'Man', emoji: '👨' },
  { name: 'Person Beard', emoji: '🧔' },
  { name: 'Person Beard', emoji: '🧔🏻' },
  { name: 'Monkey Face', emoji: '🐵' },
  { name: 'Monkey', emoji: '🐒' },
  { name: 'Gorilla', emoji: '🦍' },
  { name: 'Orangutan', emoji: '🦧' },
  { name: 'Dog Face', emoji: '🐶' },
  { name: 'Dog', emoji: '🐕' },
  { name: 'Guide Dog', emoji: '🦮' },
  { name: 'Service Dog', emoji: '🐕‍🦺' },
  { name: 'Poodle', emoji: '🐩' },
  { name: 'Wolf', emoji: '🐺' },
  { name: 'Fox', emoji: '🦊' },
  { name: 'Raccoon', emoji: '🦝' },
  { name: 'Cat Face', emoji: '🐱' },
  { name: 'Cat', emoji: '🐈' },
  { name: 'Black Cat', emoji: '🐈‍⬛' },
  { name: 'Lion', emoji: '🦁' },
  { name: 'Tiger Face', emoji: '🐯' },
  { name: 'Tiger', emoji: '🐅' },
  { name: 'Leopard', emoji: '🐆' },
  { name: 'Horse Face', emoji: '🐴' },
  { name: 'Horse', emoji: '🐎' },
  { name: 'Unicorn', emoji: '🦄' },
  { name: 'Zebra', emoji: '🦓' },
  { name: 'Deer', emoji: '🦌' },
  { name: 'Bison', emoji: '🦬' },
  { name: 'Cow Face', emoji: '🐮' },
  { name: 'Ox', emoji: '🐂' },
  { name: 'Water Buffalo', emoji: '🐃' },
  { name: 'Cow', emoji: '🐄' },
  { name: 'Pig Face', emoji: '🐷' },
  { name: 'Pig', emoji: '🐖' },
  { name: 'Boar', emoji: '🐗' },
  { name: 'Pig Nose', emoji: '🐽' },
  { name: 'Ram', emoji: '🐏' },
  { name: 'Ewe', emoji: '🐑' },
  { name: 'Goat', emoji: '🐐' },
  { name: 'Camel', emoji: '🐪' },
  { name: 'Bactrian Camel', emoji: '🐫' },
  { name: 'Llama', emoji: '🦙' },
  { name: 'Giraffe', emoji: '🦒' },
  { name: 'Elephant', emoji: '🐘' },
  { name: 'Mammoth', emoji: '🦣' },
  { name: 'Rhinoceros', emoji: '🦏' },
  { name: 'Hippopotamus', emoji: '🦛' },
  { name: 'Mouse Face', emoji: '🐭' },
  { name: 'Mouse', emoji: '🐁' },
  { name: 'Rat', emoji: '🐀' },
  { name: 'Hamster', emoji: '🐹' },
  { name: 'Rabbit Face', emoji: '🐰' },
  { name: 'Rabbit', emoji: '🐇' },
  { name: 'Chipmunk', emoji: '🐿️' },
  { name: 'Beaver', emoji: '🦫' },
  { name: 'Hedgehog', emoji: '🦔' },
  { name: 'Bat', emoji: '🦇' },
  { name: 'Bear', emoji: '🐻' },
  { name: 'Polar Bear', emoji: '🐻‍❄️' },
  { name: 'Koala', emoji: '🐨' },
  { name: 'Panda', emoji: '🐼' },
  { name: 'Sloth', emoji: '🦥' },
  { name: 'Otter', emoji: '🦦' },
  { name: 'Skunk', emoji: '🦨' },
  { name: 'Kangaroo', emoji: '🦘' },
  { name: 'Badger', emoji: '🦡' },
  { name: 'Paw Prints', emoji: '🐾' },
  { name: 'Turkey', emoji: '🦃' },
  { name: 'Chicken', emoji: '🐔' },
  { name: 'Rooster', emoji: '🐓' },
  { name: 'Hatching Chick', emoji: '🐣' },
  { name: 'Baby Chick', emoji: '🐤' },
  { name: 'Front-Facing Baby Chick', emoji: '🐥' },
  { name: 'Bird', emoji: '🐦' },
  { name: 'Penguin', emoji: '🐧' },
  { name: 'Dove', emoji: '🕊️' },
  { name: 'Eagle', emoji: '🦅' },
  { name: 'Duck', emoji: '🦆' },
  { name: 'Swan', emoji: '🦢' },
  { name: 'Owl', emoji: '🦉' },
  { name: 'Dodo', emoji: '🦤' },
  { name: 'Feather', emoji: '🪶' },
  { name: 'Flamingo', emoji: '🦩' },
  { name: 'Peacock', emoji: '🦚' },
  { name: 'Parrot', emoji: '🦜' },
  { name: 'Frog', emoji: '🐸' },
  { name: 'Crocodile', emoji: '🐊' },
  { name: 'Turtle', emoji: '🐢' },
  { name: 'Lizard', emoji: '🦎' },
  { name: 'Snake', emoji: '🐍' },
  { name: 'Dragon Face', emoji: '🐲' },
  { name: 'Dragon', emoji: '🐉' },
  { name: 'Sauropod', emoji: '🦕' },
  { name: 'T-Rex', emoji: '🦖' },
  { name: 'Spouting Whale', emoji: '🐳' },
  { name: 'Whale', emoji: '🐋' },
  { name: 'Dolphin', emoji: '🐬' },
  { name: 'Seal', emoji: '🦭' },
  { name: 'Fish', emoji: '🐟' },
  { name: 'Tropical Fish', emoji: '🐠' },
  { name: 'Blowfish', emoji: '🐡' },
  { name: 'Shark', emoji: '🦈' },
  { name: 'Octopus', emoji: '🐙' },
  { name: 'Spiral Shell', emoji: '🐚' },
  { name: 'Coral', emoji: '🪸' },
  { name: 'Snail', emoji: '🐌' },
  { name: 'Butterfly', emoji: '🦋' },
  { name: 'Bug', emoji: '🐛' },
  { name: 'Ant', emoji: '🐜' },
  { name: 'Honeybee', emoji: '🐝' },
  { name: 'Beetle', emoji: '🪲' },
  { name: 'Lady Beetle', emoji: '🐞' },
  { name: 'Cricket', emoji: '🦗' },
  { name: 'Cockroach', emoji: '🪳' },
  { name: 'Spider', emoji: '🕷️' },
  { name: 'Spider Web', emoji: '🕸️' },
  { name: 'Scorpion', emoji: '🦂' },
  { name: 'Mosquito', emoji: '🦟' },
  { name: 'Fly', emoji: '🪰' },
  { name: 'Worm', emoji: '🪱' },
  { name: 'Microbe', emoji: '🦠' },
  { name: 'Bouquet', emoji: '💐' },
  { name: 'Cherry Blossom', emoji: '🌸' },
  { name: 'White Flower', emoji: '💮' },
  { name: 'Lotus', emoji: '🪷' },
  { name: 'Rosette', emoji: '🏵️' },
  { name: 'Rose', emoji: '🌹' },
  { name: 'Wilted Flower', emoji: '🥀' },
  { name: 'Hibiscus', emoji: '🌺' },
  { name: 'Sunflower', emoji: '🌻' },
  { name: 'Blossom', emoji: '🌼' },
  { name: 'Tulip', emoji: '🌷' },
  { name: 'Seedling', emoji: '🌱' },
  { name: 'Potted Plant', emoji: '🪴' },
  { name: 'Evergreen Tree', emoji: '🌲' },
  { name: 'Deciduous Tree', emoji: '🌳' },
  { name: 'Palm Tree', emoji: '🌴' },
  { name: 'Cactus', emoji: '🌵' },
  { name: 'Ear of Rice', emoji: '🌾' },
  { name: 'Herb', emoji: '🌿' },
  { name: 'Shamrock', emoji: '☘️' },
  { name: 'Four Leaf Clover', emoji: '🍀' },
  { name: 'Maple Leaf', emoji: '🍁' },
  { name: 'Fallen Leaf', emoji: '🍂' },
  { name: 'Leaf Fluttering in Wind', emoji: '🍃' },
  { name: 'Empty Nest', emoji: '🪹' },
  { name: 'Nest with Eggs', emoji: '🪺' },
  { name: 'Grapes', emoji: '🍇' },
  { name: 'Melon', emoji: '🍈' },
  { name: 'Watermelon', emoji: '🍉' },
  { name: 'Tangerine', emoji: '🍊' },
  { name: 'Lemon', emoji: '🍋' },
  { name: 'Banana', emoji: '🍌' },
  { name: 'Pineapple', emoji: '🍍' },
  { name: 'Mango', emoji: '🥭' },
  { name: 'Red Apple', emoji: '🍎' },
  { name: 'Green Apple', emoji: '🍏' },
  { name: 'Pear', emoji: '🍐' },
  { name: 'Peach', emoji: '🍑' },
  { name: 'Cherries', emoji: '🍒' },
  { name: 'Strawberry', emoji: '🍓' },
  { name: 'Blueberries', emoji: '🫐' },
  { name: 'Kiwifruit', emoji: '🥝' },
  { name: 'Tomato', emoji: '🍅' },
  { name: 'Olive', emoji: '🫒' },
  { name: 'Coconut', emoji: '🥥' },
  { name: 'Avocado', emoji: '🥑' },
  { name: 'Eggplant', emoji: '🍆' },
  { name: 'Potato', emoji: '🥔' },
  { name: 'Carrot', emoji: '🥕' },
  { name: 'Ear of Corn', emoji: '🌽' },
  { name: 'Hot Pepper', emoji: '🌶️' },
  { name: 'Bell Pepper', emoji: '🫑' },
  { name: 'Cucumber', emoji: '🥒' },
  { name: 'Leafy Green', emoji: '🥬' },
  { name: 'Broccoli', emoji: '🥦' },
  { name: 'Garlic', emoji: '🧄' },
  { name: 'Onion', emoji: '🧅' },
  { name: 'Mushroom', emoji: '🍄' },
  { name: 'Peanuts', emoji: '🥜' },
  { name: 'Beans', emoji: '🫘' },
  { name: 'Chestnut', emoji: '🌰' },
  { name: 'Bread', emoji: '🍞' },
  { name: 'Croissant', emoji: '🥐' },
  { name: 'Baguette Bread', emoji: '🥖' },
  { name: 'Flatbread', emoji: '🫓' },
  { name: 'Pretzel', emoji: '🥨' },
  { name: 'Bagel', emoji: '🥯' },
  { name: 'Pancakes', emoji: '🥞' },
  { name: 'Waffle', emoji: '🧇' },
  { name: 'Cheese Wedge', emoji: '🧀' },
  { name: 'Meat on Bone', emoji: '🍖' },
  { name: 'Poultry Leg', emoji: '🍗' },
  { name: 'Cut of Meat', emoji: '🥩' },
  { name: 'Bacon', emoji: '🥓' },
  { name: 'Hamburger', emoji: '🍔' },
  { name: 'French Fries', emoji: '🍟' },
  { name: 'Pizza', emoji: '🍕' },
  { name: 'Hot Dog', emoji: '🌭' },
  { name: 'Sandwich', emoji: '🥪' },
  { name: 'Taco', emoji: '🌮' },
  { name: 'Burrito', emoji: '🌯' },
  { name: 'Tamale', emoji: '🫔' },
  { name: 'Stuffed Flatbread', emoji: '🥙' },
  { name: 'Falafel', emoji: '🧆' },
  { name: 'Egg', emoji: '🥚' },
  { name: 'Cooking', emoji: '🍳' },
  { name: 'Shallow Pan of Food', emoji: '🥘' },
  { name: 'Pot of Food', emoji: '🍲' },
  { name: 'Fondue', emoji: '🫕' },
  { name: 'Bowl with Spoon', emoji: '🥣' },
  { name: 'Green Salad', emoji: '🥗' },
  { name: 'Popcorn', emoji: '🍿' },
  { name: 'Butter', emoji: '🧈' },
  { name: 'Salt', emoji: '🧂' },
  { name: 'Canned Food', emoji: '🥫' },
  { name: 'Bento Box', emoji: '🍱' },
  { name: 'Rice Cracker', emoji: '🍘' },
  { name: 'Rice Ball', emoji: '🍙' },
  { name: 'Cooked Rice', emoji: '🍚' },
  { name: 'Curry Rice', emoji: '🍛' },
  { name: 'Steaming Bowl', emoji: '🍜' },
  { name: 'Spaghetti', emoji: '🍝' },
  { name: 'Roasted Sweet Potato', emoji: '🍠' },
  { name: 'Oden', emoji: '🍢' },
  { name: 'Sushi', emoji: '🍣' },
  { name: 'Fried Shrimp', emoji: '🍤' },
  { name: 'Fish Cake with Swirl', emoji: '🍥' },
  { name: 'Moon Cake', emoji: '🥮' },
  { name: 'Dango', emoji: '🍡' },
  { name: 'Dumpling', emoji: '🥟' },
  { name: 'Fortune Cookie', emoji: '🥠' },
  { name: 'Takeout Box', emoji: '🥡' },
  { name: 'Crab', emoji: '🦀' },
  { name: 'Lobster', emoji: '🦞' },
  { name: 'Shrimp', emoji: '🦐' },
  { name: 'Squid', emoji: '🦑' },
  { name: 'Oyster', emoji: '🦪' },
  { name: 'Soft Ice Cream', emoji: '🍦' },
  { name: 'Shaved Ice', emoji: '🍧' },
  { name: 'Ice Cream', emoji: '🍨' },
  { name: 'Doughnut', emoji: '🍩' },
  { name: 'Cookie', emoji: '🍪' },
  { name: 'Birthday Cake', emoji: '🎂' },
  { name: 'Shortcake', emoji: '🍰' },
  { name: 'Cupcake', emoji: '🧁' },
  { name: 'Pie', emoji: '🥧' },
  { name: 'Chocolate Bar', emoji: '🍫' },
  { name: 'Candy', emoji: '🍬' },
  { name: 'Lollipop', emoji: '🍭' },
  { name: 'Custard', emoji: '🍮' },
  { name: 'Honey Pot', emoji: '🍯' },
  { name: 'Baby Bottle', emoji: '🍼' },
  { name: 'Glass of Milk', emoji: '🥛' },
  { name: 'Hot Beverage', emoji: '☕' },
  { name: 'Teapot', emoji: '🫖' },
  { name: 'Teacup Without Handle', emoji: '🍵' },
  { name: 'Sake', emoji: '🍶' },
  { name: 'Bottle with Popping Cork', emoji: '🍾' },
  { name: 'Wine Glass', emoji: '🍷' },
  { name: 'Cocktail Glass', emoji: '🍸' },
  { name: 'Tropical Drink', emoji: '🍹' },
  { name: 'Beer Mug', emoji: '🍺' },
  { name: 'Clinking Beer Mugs', emoji: '🍻' },
  { name: 'Clinking Glasses', emoji: '🥂' },
  { name: 'Tumbler Glass', emoji: '🥃' },
  { name: 'Pouring Liquid', emoji: '🫗' },
  { name: 'Cup with Straw', emoji: '🥤' },
  { name: 'Bubble Tea', emoji: '🧋' },
  { name: 'Beverage Box', emoji: '🧃' },
  { name: 'Mate', emoji: '🧉' },
  { name: 'Ice', emoji: '🧊' },
  { name: 'Chopsticks', emoji: '🥢' },
  { name: 'Fork and Knife', emoji: '🍴' },
  { name: 'Spoon', emoji: '🥄' },
  { name: 'Hocho', emoji: '🔪' },
  { name: 'Jar', emoji: '🫙' },
  { name: 'Amphora', emoji: '🏺' },
  { name: 'Earth Globe Europe-Africa', emoji: '🌍' },
  { name: 'World Map', emoji: '🗺️' },
  { name: 'Map of Japan', emoji: '🗾' },
  { name: 'Compass', emoji: '🧭' },
  { name: 'Volcano', emoji: '🌋' },
  { name: 'Mount Fuji', emoji: '🗻' },
  { name: 'Camping', emoji: '🏕️' },
  { name: 'Beach with Umbrella', emoji: '🏖️' },
];
