//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GreenOnSoftware.Commons.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("GreenOnSoftware.Commons.Resources.ErrorMessages", typeof(ErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} failed..
        /// </summary>
        public static string ActionFailed {
            get {
                return ResourceManager.GetString("ActionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This github account is already connected with another user..
        /// </summary>
        public static string AlreadyConnectedWithAnotherAccount {
            get {
                return ResourceManager.GetString("AlreadyConnectedWithAnotherAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article already exists..
        /// </summary>
        public static string ArticleAlreadyExists {
            get {
                return ResourceManager.GetString("ArticleAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Article not found..
        /// </summary>
        public static string ArticleNotFound {
            get {
                return ResourceManager.GetString("ArticleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avatar name is required..
        /// </summary>
        public static string AvatarNameIsRequired {
            get {
                return ResourceManager.GetString("AvatarNameIsRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User has not confirmed email..
        /// </summary>
        public static string EmailIsNotConfirmed {
            get {
                return ResourceManager.GetString("EmailIsNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forbidden.
        /// </summary>
        public static string Forbidden {
            get {
                return ResourceManager.GetString("Forbidden", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid file format..
        /// </summary>
        public static string InvalidFileFormat {
            get {
                return ResourceManager.GetString("InvalidFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid password..
        /// </summary>
        public static string InvalidPassword {
            get {
                return ResourceManager.GetString("InvalidPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} can&apos;t be null..
        /// </summary>
        public static string ParameterCannotBeNull {
            get {
                return ResourceManager.GetString("ParameterCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} does not exist..
        /// </summary>
        public static string ParameterDoesNotExist {
            get {
                return ResourceManager.GetString("ParameterDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture file is empty..
        /// </summary>
        public static string PictureFileEmpty {
            get {
                return ResourceManager.GetString("PictureFileEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture file size is over 5 MB..
        /// </summary>
        public static string PictureSizeTooBig {
            get {
                return ResourceManager.GetString("PictureSizeTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Picture width or height is over 2000 px..
        /// </summary>
        public static string PictureWidthOrHeightTooBig {
            get {
                return ResourceManager.GetString("PictureWidthOrHeightTooBig", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during removing picture.
        /// </summary>
        public static string RemovePictureError {
            get {
                return ResourceManager.GetString("RemovePictureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sending email failed..
        /// </summary>
        public static string SendEmailFailed {
            get {
                return ResourceManager.GetString("SendEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occured during uploading picture..
        /// </summary>
        public static string UploadPictureError {
            get {
                return ResourceManager.GetString("UploadPictureError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is signed in..
        /// </summary>
        public static string UserIsSignedIn {
            get {
                return ResourceManager.GetString("UserIsSignedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User session already exists..
        /// </summary>
        public static string UserSessionAlreadyExists {
            get {
                return ResourceManager.GetString("UserSessionAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        public static string WrongCredentials {
            get {
                return ResourceManager.GetString("WrongCredentials", resourceCulture);
            }
        }
    }
}
