name: Code check

on:
  pull_request:
    branches: ["develop"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd system
          npm install --legacy-peer-deps
      - name: Run code check
        run: |
          cd system
          npm run lint:checkAll