name: Tests e2e

on:
  pull_request:
    branches: ["develop", "main"]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: |
          cd system
          npm install --legacy-peer-deps
      - name: 'Create env file'
        run: |
          cd system
          touch .env
          echo NEXT_PUBLIC_API_URL=${{ secrets.NEXT_PUBLIC_API_URL }} >> .env
          cat .env
      - name: Cypress e2e tests
        run: |
          cd system
          npm run e2e:checkAll